export const ERRORS = {
  UNHANDLED: 'UNHANDLED',
  VALIDATION: 'VALIDATION'
};

export const METRIC_TYPES = {
  HUMIDITY: 'HUMIDITY',
  TEMPERATURE: 'TEMPERATURE'
};

export const TIMESTAMP_FORMAT = 'yyyy-MM-dd HH:mm:ss';
